In [15]:
import numpy as np
import pandas as pd


df = pd.read_csv("C:\\Users\PMLS\Desktop\Data_Sets\Records of Pateint.csv")

df = df.drop(columns=['Name'])

X = df.drop('Dead', axis=1).values
y = df['Dead'].values.reshape(-1, 1)

df

,Age,Sugar,Cholesterol,BP,Weight,Height (in feet),Urea,Creatinine,TLC,Dead
0,45,110.88,204.79,152.64,99.40,5.15,31.15,0.82,5362.50,1
1,75,154.22,234.19,139.54,118.28,5.26,44.93,1.46,9700.33,1
2,59,143.28,197.53,178.75,59.43,4.84,12.44,0.83,4860.84,1
3,67,128.21,234.18,114.32,77.10,6.14,30.87,0.66,7295.04,0
4,31,78.66,177.32,121.88,112.28,5.73,37.79,1.05,10988.42,0
...,...,...,...,...,...,...,...,...,...,...
1995,74,107.53,189.41,172.42,149.69,5.33,46.82,0.59,7159.46,0
1996,83,111.89,212.33,123.88,124.89,5.12,43.61,1.33,8829.28,0
1997,26,142.92,247.08,167.89,110.86,5.12,34.06,0.61,7759.87,1
1998,27,130.25,193.14,147.19,108.11,5.88,37.65,1.45,8254.70,0
1999,71,112.91,277.01,125.44,89.08,5.93,38.17,0.95,4657.24,0

## Normalization

In [ ]:
X = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
X = np.hstack([np.ones((X.shape[0], 1)), X])

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Sigmoid , Cost , and Gradient Descent

In [45]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


def compute_cost(X, y, weights):
    m = len(y)
    z = np.dot(X, weights)
    h = sigmoid(z)
    cost = (-1/m) * np.sum(y * np.log(h) + (1 - y) * np.log(1 - h))
    return cost

def gradient_descent(X, y, weights, learning_rate, iterations):
    m = len(y)
    cost_history = np.zeros((iterations, 1))
    
    for i in range(iterations):
        z = np.dot(X, weights)
        h = sigmoid(z)
        gradient = np.dot(X.T, (h - y)) / m
        weights -= learning_rate * gradient
        
      
        cost_history[i] = compute_cost(X, y, weights)
    
    return weights, cost_history

## Initialization and Prediction

In [73]:

learning_rate = 0.01
iterations = 10000
weights = np.zeros((X_train.shape[1], 1))

weights, cost_history = gradient_descent(X_train, y_train, weights, learning_rate, iterations)

def predict(X, weights):
    z = np.dot(X, weights)
    h = sigmoid(z)
    return [1 if i > 0.5 else 0 for i in h]

y_pred = predict(X_test, weights)

y_pred = np.array(y_pred).reshape(-1, 1)

### Accuracy , Precision , and Recall

In [76]:
accuracy = np.mean(y_pred == y_test) * 100
TP = np.sum((y_test == 1) & (y_pred == 1))
TN = np.sum((y_test == 0) & (y_pred == 0))
FP = np.sum((y_test == 0) & (y_pred == 1))
FN = np.sum((y_test == 1) & (y_pred == 0))
print(TP,TN,FP,FN)
precision = TP / (TP + FP) if (TP + FP) > 0 else 0
recall = TP / (TP + FN) if (TP + FN) > 0 else 0
f1_score = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

# Output the results
print(f"Accuracy: {accuracy:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1_score:.2f}")

63 153 56 128
Accuracy: 54.00%
Precision: 0.53
Recall: 0.33
F1-Score: 0.41